name: "ADC & LIN"
version: "1.0.2"
slug: "adc_lin"
description: "Add-on for visualizing ADC and LIN communication"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: "services"
ingress: true
#panel_icon: "mdi:chart-line"  
panel_icon: mdi:chip
panel_title: "ADC & LIN"
ingress_port: 8099
ports:
  8765/tcp: 8765  # WebSocket 
homeassistant_api: true
host_network: true
map:
  - spi
  - config
  - dev
options: {}
schema: {}
devices:
  - /dev/spidev1.1:/dev/spidev1.1
  - /dev/spidev1.0:/dev/spidev1.0
  - /dev/ttyAMA2:/dev/ttyAMA2
