name: "ADC & LIN_advanced"
version: "1.0.6.6"
slug: "adc_lin_advanced"
description: "Add-on for visualizing ADC and LIN communication with automatic HA discovery"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: "services"
ingress: true
panel_icon: mdi:chip
panel_title: "advanced ADC & LIN"
ingress_port: 8099
ports:
  8765/tcp: 8765  # WebSocket 
homeassistant_api: true
host_network: true
map:
  - spi
  - config
  - dev
options:
  mqtt_user: "mqtt"     
  mqtt_pass: "mqtt_pass"
  ema_alpha_voltage: 0.1
  ema_alpha_resistance: 0.1
  moving_average_window_voltage: 10
  moving_average_window_resistance: 10
  low_pass_alpha: 0.1
schema:
  mqtt_user: str
  mqtt_pass: str
  ema_alpha_voltage: float
  ema_alpha_resistance: float
  moving_average_window_voltage: int
  moving_average_window_resistance: int
  low_pass_alpha: float
environment:
  MQTT_USER: "${mqtt_user}"
  MQTT_PASS: "${mqtt_pass}"
  EMA_ALPHA_VOLTAGE: "${ema_alpha_voltage}"
  EMA_ALPHA_RESISTANCE: "${ema_alpha_resistance}"
  MOVING_AVERAGE_WINDOW_VOLTAGE: "${moving_average_window_voltage}"
  MOVING_AVERAGE_WINDOW_RESISTANCE: "${moving_average_window_resistance}"
  LOW_PASS_ALPHA: "${low_pass_alpha}"
devices:
  - /dev/spidev1.1:/dev/spidev1.1
  - /dev/spidev1.0:/dev/spidev1.0
  - /dev/ttyAMA2:/dev/ttyAMA2
