name: "ADC"
version: "0.0.0.1"
slug: "adc"
description: "Add-on for monitoring ADC and MQTT broker "
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: "services"
host_network: true
map:
  - spi
  - config
  - dev
ports:
  8091/tcp: 8091  
devices:
  - /dev/spidev1.1:/dev/spidev1.1
  - /dev/spidev1.0:/dev/spidev1.0
  - /dev/ttyAMA2:/dev/ttyAMA2
